export const siteConfig = {
  name: "Rayyan",
  title: "AI/ML & Full-Stack Engineer",
  description:
    "Portfolio of Rayyan, a UMass Amherst computer science student building privacy-conscious machine learning systems, local AI tools, and full-stack applications.",
  accentColor: "#60a5fa",
  social: {
    phone: "+1 (413) 253-6440",
    email: "frayyan@umass.edu",
    linkedin: "https://linkedin.com/in/rayyanfs",
    github: "https://github.com/frayyan-rgb",
  },
  aboutMe:
    "I'm a Computer Science student at UMass Amherst who builds practical, privacy-conscious software and machine learning systems. My work spans local-LLM pipelines, on-device AI, full-stack products, and research. I enjoy turning complex technical ideas into reliable tools people can actually use. Outside of coding, I enjoy working out and playing guitar.",
  skills: [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "HTML/CSS",
    "React",
    "Next.js",
    "Node.js",
    "Electron",
    "Tailwind CSS",
    "REST APIs",
    "MongoDB",
    "Supabase",
    "Firebase",
    "PyTorch",
    "scikit-learn",
    "MNE",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Hugging Face",
    "Git",
    "Linux",
    "llama.cpp",
    "OpenRouter",
    "FFmpeg/FFprobe",
    "MLX Whisper",
    "TrackPy",
    "ImageJ/Fiji",
    "PDF.js",
  ],
  projects: [
    {
      name: "Folio",
      subtitle: "Privacy-First Desktop PDF Reader",
      context: "Personal Project",
      description:
        "A desktop PDF reader that keeps documents and AI processing on the user's device.",
      bullets: [
        "Enabled users to annotate documents and generate on-device AI explanations, with no document data leaving the device.",
        "Delivered on-device document explanations in under 4 seconds by selecting Gemma 4 E2B and E4B QAT models for a bundled llama.cpp runtime with an 8,192-token context window.",
        "Eliminated terminal-based model setup by building an in-app workflow to download, load, and manage local models, with streamed progress tracking and automatic cleanup on failed or cancelled downloads.",
      ],
      links: [
        { label: "GitHub", url: "https://github.com/frayyan-rgb/Folio" },
        { label: "Demo", url: "https://youtu.be/sDCy42qXLDs" },
      ],
      skills: [
        "Electron",
        "React",
        "TypeScript",
        "Node.js",
        "PDF.js",
        "llama.cpp",
        "Tailwind CSS",
      ],
    },
    {
      name: "Closure",
      subtitle: "AI-Powered Workforce-Scheduling Platform",
      context: "1st Place, Hack(H)er413",
      description:
        "A real-time scheduling platform that helps teams create, manage, and update employee schedules.",
      bullets: [
        "Built a tool to help teams create, manage, and update employee schedules through a real-time web interface.",
        "Achieved approximately 80% accuracy in recommending employees for shifts by integrating OpenRouter to rank candidates based on skills and availability, evaluated against a labeled set of assignments.",
        "Shipped a responsive task-card interface that managed real-time state for tasks across employees during the live demo, with priority badges, overdue indicators, and inline editing, persisting changes to Supabase.",
      ],
      links: [
        { label: "GitHub", url: "https://github.com/anejmeldeen/closure" },
        { label: "Demo", url: "https://www.youtube.com/watch?v=VMH02jTByus" },
      ],
      skills: [
        "React",
        "Next.js",
        "TypeScript",
        "Supabase",
        "Node.js",
        "OpenRouter",
      ],
    },
    {
      name: "Campus Club Finder",
      subtitle: "Campus Organization Discovery Platform",
      context: "Personal Project",
      description:
        "A responsive platform that helps UMass students discover and explore campus clubs and organizations.",
      bullets: [
        "Built a responsive platform enabling UMass students to discover and explore more than 50 campus clubs and organizations.",
        "Implemented tag-based recommendations, persistent saved clubs, and filtering by category, meeting time, and commitment level.",
      ],
      links: [
        { label: "GitHub", url: "https://github.com/nealp/clubFinderApp" },
      ],
      skills: ["React", "Next.js", "Tailwind CSS", "Supabase"],
    },
  ],
  experience: [
    {
      company: "UMass Amherst Information Technology",
      title: "Student Ambassador",
      dateRange: "Aug. 2026 - Present",
      location: "Amherst, Ma",
      technologies: [
        "Public Speaking",
        "Marketing",
        "Technology Marketing",
        "Social Media Outreach",
        "Technical Communication",
        "Teamwork",
      ],
      links: [],
      bullets: [
        "Promote new technology tools and IT resources to UMass students through campus events and social media.",
        "Test university services, provide feedback to IT staff, and help improve the overall student technology experience.",
      ],
    },
    {
      company: "UMass Amherst",
      title: "Machine Learning Researcher",
      dateRange: "May 2026 - Sep. 2026",
      location: "Amherst, MA",
      technologies: ["PyTorch", "MNE", "scikit-learn"],
      links: [
        {
          label: "Poster",
          url: "https://drive.google.com/file/d/1yw9VEsgMnXjOw8HfR0TnEHiCtuDKS9zF/view?usp=sharing",
        },
      ],
      bullets: [
        "Built a privacy evaluation pipeline using PyTorch, MNE, and scikit-learn to classify motor-imagery EEG signals from 9 participants while measuring how much participant identity the data revealed.",
        "Compressed the neural network's learned EEG features from 64D to 8D, reducing participant identification accuracy from 72.4% to 61.5% while improving motor-imagery classification accuracy from 50.1% to 54.1%.",
        "Tested a stochastic version of the 8D privacy model across 10 random seeds, reducing participant identification accuracy from 61.5% to 39.2% while retaining 48.3% motor-imagery accuracy, compared with a 25% chance baseline.",
      ],
    },
    {
      company: "Myco - Web3 Video Streaming & Entertainment Platform",
      title: "Software Engineer Intern",
      dateRange: "Jun. 2026 - Aug. 2026",
      location: "Karachi, Pakistan",
      technologies: ["Python", "LM Studio", "FFmpeg", "MLX Whisper"],
      links: [],
      bullets: [
        "Enriched 20,000+ videos with 43 metadata fields by building a Python classification pipeline using LM Studio-hosted local LLMs and API models to assign content type, context, and genre from a predefined taxonomy.",
        "Reduced pipeline crashes from approximately 1 in 5 runs to near zero by tuning LLM context-window limits, stream handling, and prompt design, while adding schema validation, retries, and checkpoint recovery.",
        "Cut per-video metadata processing time from approximately 4 minutes to 2 minutes for a 20-minute video by unifying video metadata extraction and transcription in one script using Python, FFmpeg, FFprobe, and MLX Whisper.",
      ],
    },
    {
      company: "Kandula Research Group",
      title: "Research Intern",
      dateRange: "Oct. 2025 - May 2026",
      location: "Amherst, MA",
      technologies: ["Python", "TrackPy", "NumPy", "Pandas", "ImageJ/Fiji"],
      links: [],
      bullets: [
        "Identified and characterized 4 recurring six-particle structures, including a previously unobserved active-system pattern, by using NumPy and Pandas to build and analyze neighbor-based connectivity graphs.",
        "Compressed particle-tracking analysis time from over 2 hours to approximately 5 minutes per dataset by automating particle detection, tracking, and structural analysis across dozens of microscopy datasets using Python, TrackPy, and ImageJ/Fiji.",
        "Validated classifications by using Matplotlib to overlay computed clusters onto raw microscopy frames, then ranking recurring structures across an average of 15 six-particle clusters per frame.",
      ],
    },
    {
      company: "Astrik Digital",
      title: "Software Engineer Intern",
      dateRange: "Jan. 2025 - Apr. 2025",
      location: "Karachi, Pakistan",
      technologies: ["React", "TypeScript", "Firebase", "MongoDB"],
      links: [],
      bullets: [
        "Diagnosed live, client-facing API failures, broken forms, and CRM integration issues across 15+ websites within minutes, delivering rapid root-cause reports that unblocked lead-capture and conversion workflows.",
        "Modernized an internal food-ordering kiosk used by employees to browse menus and place workplace meal orders by rebuilding the C# application as a React and TypeScript single-page application integrated with Firebase and MongoDB.",
        "Slashed recurring crash and infinite-load incidents to near zero by replacing full-page reloads with client-side navigation and selective data loading, eliminating redundant network requests that failed on unstable in-store connections.",
      ],
    },
    {
      company: "BuildUMass | Global Veterinary Fund (Nonprofit)",
      title: "Volunteer Software Developer",
      dateRange: "Feb. 2026 - Present",
      location: "Amherst, MA",
      technologies: [],
      links: [],
      bullets: [
        "Building a full-stack website with application forms, payment integration, an events system, and an authenticated admin panel.",
      ],
    },
    {
      company: "UMass Pitch",
      title: "Secretary",
      dateRange: "Apr. 2026 - Present",
      location: "Amherst, MA",
      technologies: [],
      links: [],
      bullets: [
        "Maintain meeting records, communicate updates to members, and help coordinate rehearsals, performances, and club activities.",
      ],
    },
  ],
  education: [
    {
      school: "University of Massachusetts Amherst",
      degree:
        "Bachelor of Science in Computer Science, Commonwealth Honors College | GPA: 3.95/4.00",
      dateRange: "Expected May 2028",
      achievements: [
        "Honors: Chancellor's Award ($18,000/year merit scholarship), Dean's List every semester",
        "Relevant Coursework: Data Structures & Algorithms, Reasoning Under Uncertainty, Intro to Computation, Introduction to C Programming, Discrete Mathematics, Object-Oriented Programming, Linear Algebra, Multivariate Calculus",
      ],
    },
  ],
};
